version: "3"
services:
  webapp:
      image: '${DOCKER_IMAGE_NAME}/mywebapp1:${BUILD_NUMBER}'
      tty: true
      working_dir: /application
      volumes:
        - .:/application
      ports:
        - 5001:5000
      env_file: .env
      command: python webapp.py
